version: '3'
services:
  katanox_test_db:
    image: postgres:13.5
    container_name: katanox_test_db
    environment:
      - POSTGRES_USER=katanox-user
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=katanox_test
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  katanox-api-server6:
    container_name: katanox-api-server6
    build:
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"

volumes:
  postgres:
    driver: local
